stages:
  - docker-build
before_script:
  - aliimage=registry.docker.quancheng-ec.com:5000/yugong:`TZ=CST-8 date '+%Y%m%d'`
  - hostname -i
  - whoami
build_image:
  stage: docker-build
  
  script:
    - echo `git rev-parse --short HEAD` >> bin/git.tag
    - echo $image
    - if [ "`docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }' ); fi
    - gradle clean build -x test --refresh-dependencies 
    - echo "Build Docker Image..."
    - docker build --no-cache -t $aliimage .
    - echo "Push Image:" $aliimage " to repository..."
    - docker push $aliimage
  only:
    - master